config/routes.rb
Rails.application.routes.draw do

  get '/join' => 'users#join'
  post '/join' => 'users#create'

  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#delete'

  post '/write' => 'timeline#create'
  post '/comment' => 'timeline#comment'

  get '/my/:id' => 'pages#user_page'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :timeline
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper, PagesHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @timelines = Timeline.all
  end

  def user_page
    user(params[:id])

    if user_isvalue?
      redirect_to :root
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to :root
    else
      flash.now[:alert] = "이메일 또는 패스워드가 잘못되었습니다."
      render 'login'
    end
  end

  def delete
    log_out
    redirect_to :root
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def create
    if user_signed_in?
      Timeline.create(id_num: current_user.id ,name: current_user.name, content: params[:texts])
      redirect_to :root
    end
  end
  def comment
    if user_signed_in?
      Comment.create(id_num: current_user.id , name: current_user.name, timeline_id: params[:timeline_id], msg: params[:msg])
      redirect_to :root
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def join
  end

  def profile_set
    if user_signed_in?

    else
      redirect_to :back
    end
  end

  def create
    if params[:gender] == "man"
      profile = "bagic_man.jpg"
    else
      profile = "bagic_woman.jpg"
    end
    User.create(name: params[:name],
          email: params[:email],
          password: params[:password],
          password_confirmation: params[:password_confirmation],
          gender: params[:gender],
          profile: profile)
    redirect_to :root
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def user(id)
    @user = User.find_by(id: id)
  end

  def user_isvalue?
    user.nil?
  end
  def user_timelines
    @user_timelines = Timeline.find_by(id_num: user.id)
  end
  def user_timelines?
    !user_timelines.nil?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_email] = user.email
  end

  def current_user
    @current_user = User.find_by(email: session[:user_email])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_email)
  end
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Swallow</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- bootstrap CDN -->

        <!-- 합쳐지고 최소화된 최신 CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

        <!-- 부가적인 테마 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

        <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    </head>

    <body>
        <% if user_signed_in? %>
        <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        Menu
                        <i class="fa fa-bars"></i>
                    </button>
                    <%= link_to 'Swallow', root_path, class: "navbar-brand" %>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="hidden">
                            <a href="#page-top"></a>
                        </li>
                        <li class="page-scroll">
                        </li>
                        <li class="page-scroll">
                            <%= link_to 'logout', logout_path, method:'delete' %>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /.container-fluid -->
        </nav>
        <% else %>
        <!-- Navigation -->
        <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        Menu
                        <i class="fa fa-bars"></i>
                    </button>
                    <%= link_to 'Swallow', root_path, class: "navbar-brand" %>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="hidden">
                            <a href="#page-top"></a>
                        </li>
                        <li class="page-scroll">
                            <%= link_to 'login', login_path %>
                        </li>
                        <li class="page-scroll">
                            <%= link_to 'join', join_path %>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
        <% end %>

        <%= yield %>
    </body>
</html>

app/views/pages/index.html.erb
<% if user_signed_in? %>
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= image_tag current_user.profile , width:"50%", alt:"profile"%>
                <div class="intro-text">
                    <span class="name"><%= current_user.name %></span>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>타임라인</h2>
                <br>
            </div>
        </div>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>timelinepost</label>
                <%= form_tag '/write', method: 'post' do %>
                <input type="text" class="form-control" placeholder="오늘은 무슨 일이 있었나요?" id="texts" name="texts" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-12">
                <button type="submit" class="btn btn-fail btn-lg">전송</button>
                <% end %>
            </div>
        </div>
    </div>
</section>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>최근 글</h2>
                <br>
            </div>
        </div>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
                <% @timelines.each do |b| %>
                <h3><strong>[<%= b.name %>]</strong><%= b.content %></h3>
                <%= form_tag '/comment', methos: 'post' do %>
                <ul>
                    <% b.comments.each do |p| %>
                    <li><h4><strong>[<%= p.name %>]</strong><%= p.msg %></li></h4>
                    <% end %>

                    <input type="hidden" name="timeline_id" value="<%= b.id %>">
                    <li><input class="form" type="text" name="msg" class="form-control" placeholder="댓글을 달아주세요."></li>

                </ul>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-fail btn-sg">전송</button>
                    </div>
                </div>
                <% end %>
                <% end %>
            </div>
        </div>
    </section>
</div>
<% else %>
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= image_tag 'index.jpeg', width:"50%", class: "img-responsive", alt: "Swallow main" %>
                <div class="intro-text">
                    <span class="name">Start Swallow</span>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>로그인</h2>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <%= form_tag login_path do %>
                <%= flash[:alert] %><br>

                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Email</label>
                        <input type="email" class="form-control" placeholder="이메일" id="email" name="email" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="비밀번호" id="password" name="password" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-success btn-lg">로그인</button>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>회원가입</h2>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <%= form_tag join_path do %>
                <%= flash[:alert] %><br>

                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>이름</label>
                        <input type="text" class="form-control" placeholder="이름" id="name" name="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>이메일</label>
                        <input type="email" class="form-control" placeholder="이메일" id="email" name="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>비밀번호</label>
                        <input type="password" class="form-control" placeholder="비밀번호" id="password" name="password" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>비밀번호 확인</label>
                        <input type="password" class="form-control" placeholder="비밀번호 확인" id="password_confirmation" name="password_confirmation" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>성별</label>
                        남자 :
                        <input type="radio" name="gender" value="man" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>성별</label>
                        여자 :
                        <input type="radio" name="gender" value="woman" required data-validation-required-message="Please enter your email address."><br>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-success btn-lg">로그인</button>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>
<% end %>

app/views/pages/user_page.html.erb
<br><br><br><br><br><br><br>
<%= @user.name %>
<%= @user.gender %>
<%= @user.email %>
<%= image_tag @user.profile , width:"10%", alt:"profile"%>
<% if user_timelines? %>
  <%= user_timelines.name %>
  <%= user_timelines.id_num %>
<% end %>

app/views/users/join.html.erb
<section id="contact">
    <div class="container" >
        <div class="row">
            <div class="col-lg-12 text-center">
              <br><br>
                <h2>회원가입</h2>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <%= form_tag join_path do %>
                <%= flash[:alert] %><br>

                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>이름</label>
                        <input type="text" class="form-control" placeholder="이름" id="name" name="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>이메일</label>
                        <input type="email" class="form-control" placeholder="이메일" id="email" name="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>비밀번호</label>
                        <input type="password" class="form-control" placeholder="비밀번호" id="password" name="password" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>비밀번호 확인</label>
                        <input type="password" class="form-control" placeholder="비밀번호 확인" id="password_confirmation" name="password_confirmation" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>성별</label>
                        남자 : <input type="radio" name="gender" value="man" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>성별</label>
                        여자 : <input type="radio" name="gender" value="woman" required data-validation-required-message="Please enter your email address."><br>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-success btn-lg">로그인</button>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>